---
title: "Notes_presentation_HES"
author: "Aurélien Goutsmedt and Alexandre Truc"
date: "01/12/2021"
output: pdf_document
---

#### The goal of the paper

Formulation in the abstract: Our contribution aims at investigating the role that the EER played in fostering the emergence of a European economics inspired by the academic standards of the US, but with its own distinctive identity. *But...* : hard to observe the "influence" of EER in this process. Perhaps better to focus just on the "distinctive identity" part.

#### Methods

Mix of qualitative and quantitative methods

Mix of intellectual/analytical and institutional/sociological history: identifying the specificity of European macro, and understand how it is anchored in different network of researchs, promoted by different institutions.

#### On the origins of the EER

In 1969, two Belgian economists from the Université Libre de Bruxelles (ULB), Jean Walbroeck and Herbert Glejser, launched a new economic journal, the European Economic Review. The journal was backed by the European Scientific Association of Applied Economics (ASEPELT), created in 1961 by Waelbroeck and Etienne Kirschen (also from ULB). Before 1969, the Association published a bulletin and symposia (in English) gathering research in econometrics and mathematical economics. Similarly, the EER was seen as a way to promote the work of European scholars in econometrics and mathematical economics, as well as English as the "lingua franca of economics" that would support the process of "internationalisation of our science" (Waelbroeck and Glejser, 1969, 1).

Publication only in English in European journals was not frequent at this time. Classic opposition underlined by Fourcade 2006 between nationally- and internationally-oriented economists.

**Important** to balance this US style of economics as a model, and the wish to foster cooperation and development of a European identity in (macro)economics.

Find evidence in Waelbroeck's archives of this US model (AER model).

#### Waelbroeck's portrait

However, the econometric expertise of the CORE was much indebted with the development of a research programme in econometrics and macroeconometric modelling at the nearby Université Libre de Bruxelles (ULB), under the lead of Waelbroeck (Maes and Buyst, 2005, 79).

#### Evolution of the EER

-   DId it become more and more cited? At least in Europe?

-   The evolution of its board, with the 1980s change (there is a kind of introduction to an issue detailing the changes in the board)?

-   The change in the US affiliated economists publishing in the EER more and more. The rise in collaborations in the early 1980s.
