---
title: "Test on interactive EER networks"
output: 
  html_document:
    theme: readable
    code_folding: hide
author: "Aurélien Goutsmedt and Alexandre Truc"
date: "last complied on `r format(Sys.Date())`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
```

```{r source-and-packages}
source("~/macro_AA/EER_Paper/Script_paths_and_basic_objects_EER.R")
source("~/macro_AA/functions/functions_for_network_analysis.R")

institutions <- fread(paste0(data_path,"EER/Corpus_EER/EER_INST_XP.csv", quote="")) %>% data.table
list_graph <- readRDS(paste0(data_path,"EER/2_Raw_Networks_and_Alluv/list_networks.rds"))
alluv_dt <- readRDS(paste0(data_path,"EER/2_Raw_Networks_and_Alluv/alluv_dt.rds"))
alluv_dt <- alluv_dt[share_leiden_max >=0.05 & n_years >= 3][,c("Leiden1","Window","Id")]
```

```{r prepare-data, eval = TRUE}

list_graph <- lapply(list_graph, function(tbl)(tbl %>% activate(nodes) %>% mutate(size = replace(size, size == 0, 1))))
list_graph <- lapply(list_graph, function(tbl) (tbl %>% activate(nodes) %>% mutate(x = rescale(x, to = c(0,1000)), y = rescale(y, to = c(0,1000)))))

# creating a table with the data for nodes and edges for each window

nodes_lf <- lapply(list_graph, function(tbl) (tbl %>% activate(nodes) %>% as.data.table()))
nodes_lf <- lapply(nodes_lf, function(dt) (dt[, .(ID_Art, x, y, size, Label, Titre, Nom_ISI)]))
nodes_lf <- rbindlist(nodes_lf, idcol = "window")
nodes <- merge(nodes_lf, alluv_dt, by.x = c("ID_Art","window"), by.y = c("Id","Window"), all.x = TRUE) 

nodes <- nodes[, window := paste0(window, "-", as.integer(window) + 6)][order(ID_Art, window)]

nodes <- nodes %>% 
  mutate(Leiden1 = replace(Leiden1, is.na(Leiden1), "small communities"))

color <- c("gray",scico(n = length(unique(nodes$Leiden1)) - 1, palette = "roma") %>% 
  sample())

nodes$Leiden1 <- factor(nodes$Leiden1, levels = c(unique(nodes[Leiden1 == "small communities"]$Leiden1), unique(nodes[Leiden1 != "small communities"]$Leiden1)))

nodes[Leiden1 != "small communities", `:=` (com_x = median(x), com_y = median(y)), by = c("Leiden1","window")]

#nodes <- highlight_key(nodes, ~Leiden1)
```

```{r graphs, eval = TRUE, out.width = "120%" }
plot_ly(nodes, 
                  x = ~x, 
                  y = ~y,
                  type = "scatter",
                  mode = "markers",
                  text = ~paste('</br>', Label,
                                '</br>', str_wrap(Titre, width = 30),
                                '</br> Community:', Leiden1),
                  hoverinfo = "text",
                  size = ~log(size),
                  sizes = c(30,300),
                  frame = ~window,
                  ids = ~ID_Art,
                  color = ~Leiden1,
                  colors = color,
                  showlegend = TRUE) %>% 
  add_text(x = ~com_x,
           y = ~com_y,
           text = ~Leiden1,
           textfont = list(size = 20),
           frame = ~window,
           ids = ~Leiden1,
           showlegend = FALSE)  %>% 
  add_trace(alpha = 0.8) %>% 
  layout(yaxis = list(zeroline = FALSE,
                      showgrid = FALSE),
         xaxis = list(zeroline = FALSE,
                      showgrid = FALSE)) %>% 
  config(scrollZoom = TRUE) %>% 
 # highlight(on = "plotly_selected", 
  #          selectize = TRUE, 
   #         persistent = TRUE) %>% 
  animation_opts(frame = 2000,
                 transition = 1000,
                 redraw = TRUE,
                 mode = "next") 

#htmlwidgets::saveWidget(graphs,paste0(picture_path,"moving_graphs.html"), selfcontained = FALSE)
```


```{r institutions, eval = TRUE}
inst_by_window <- merge(nodes_lf[, c("ID_Art","window")],
                      institutions[, ID_Art := as.character(ID_Art)][, c("ID_Art","Institution","Pays","Ordre")], 
                      by = "ID_Art", allow.cartesian = TRUE)

inst_by_window[, window := paste0(window, "-", as.integer(window) + 6)]

inst_by_window[, `:=` (n = .N), by = "window"] %>% 
  .[Institution != "NULL", n_inst := round(.N/n,2), by = c("window","Institution")] %>% 
  .[Pays != "NULL", n_country := round(.N/n,2), by = c("window","Pays")] 

n_inst <- inst_by_window %>% 
  select(Institution,window,n_inst) %>% 
  unique() %>% 
  group_by(window) %>% 
  arrange(window,desc(n_inst)) %>% 
  top_n(5) %>% 
  mutate(type = "Institution") %>% 
  rename("entity" = Institution,
         "frequency" = n_inst)

n_country <- inst_by_window %>% 
  select(Pays,window,n_country) %>% 
  unique() %>% 
  group_by(window) %>% 
  arrange(window, desc(n_country)) %>% 
  top_n(5) %>% 
  mutate(type = "Country") %>% 
  rename("entity" = Pays,
         "frequency" = n_country)

inst_by_window <- rbind(n_inst,n_country) %>% as.data.table()

# Wrap data frame in SharedData
sd <- SharedData$new(inst_by_window)

# Create a filter input
bscols(widths = c(4,NA),
  list(filter_checkbox(id = "window", label = "Window", sharedData = sd, group = ~window, columns = 2),
  filter_checkbox("type", "Institution or Country", sd, ~type, columns = 2)),
  datatable(sd, extensions="Scroller", width="100%", class = "compact",
            options=list(deferRender=TRUE, scrollY=600, scroller=TRUE))
)

```

